# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-11 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, verbose_name='Nombre')),
                ('age', models.IntegerField(default=0, verbose_name='Edad')),
                ('phone', models.CharField(max_length=10, verbose_name='Telefono')),
            ],
        ),
    ]
